// src/pages/SalesData.jsx
import React, { useEffect, useState } from 'react'
import { 
  Card, 
  Table, 
  Button, 
  Input, 
  Select, 
  Space, 
  Modal, 
  Form, 
  DatePicker,
  InputNumber,
  message,
  Popconfirm,
  Upload,
  Row,
  Col,
  Statistic,
  ConfigProvider
} from 'antd'
import { 
  PlusOutlined, 
  EditOutlined, 
  DeleteOutlined, 
  UploadOutlined,
  DownloadOutlined,
  SearchOutlined,
  ReloadOutlined
} from '@ant-design/icons'
import { useSalesDataStore } from '../stores/salesDataStore'
import { useBrandManagementStore } from '../stores/brandManagementStore'
import { exportToExcel, ExcelUtils } from '../utils/excel'
import dayjs from 'dayjs'
import zhCN from 'antd/es/locale/zh_CN'

const { Option } = Select
const { RangePicker } = DatePicker

export default function SalesData() {
  const {
    salesDataList,
    loading,
    total,
    currentPage,
    pageSize,
    searchParams,
    statistics,
    fetchSalesDataList,
    fetchStatistics,
    createSalesData,
    updateSalesData,
    deleteSalesData,
    batchImportSalesData,
    batchDeleteSalesData,
    setSearchParams,
    setPagination,
    getBrandList,
    getEmployeeList,
    getShopList
  } = useSalesDataStore()

  const { getBrandOptions, selectedBrandId, setSelectedBrandId, loadBrands } = useBrandManagementStore()

  const [form] = Form.useForm()
  const [isModalVisible, setIsModalVisible] = useState(false)
  const [isEdit, setIsEdit] = useState(false)
  const [selectedRowKeys, setSelectedRowKeys] = useState([])
  const [searchForm] = Form.useForm()
  // 导入相关
  const [importModalVisible, setImportModalVisible] = useState(false)
  const [importForm] = Form.useForm()
  const [importFile, setImportFile] = useState(null)
  const [importLoading, setImportLoading] = useState(false)

  // 页面加载时获取数据
  useEffect(() => {
    // 确保品牌数据加载（与Vue一致：按用户隔离加载品牌）
    loadBrands()
    // 默认以 selectedBrandId 作为筛选
    if (selectedBrandId) {
      setSearchParams({ brandId: selectedBrandId })
    }
    fetchSalesDataList()
    fetchStatistics()
  }, [])

  // 计算默认日期
  const calculateDateByCycleType = (date, cycleType) => {
    if (cycleType === 'BY_WEEK') {
      return dayjs(date).startOf('week').add(1, 'day').format('YYYY-MM-DD')
    }
    return dayjs(date).format('YYYY-MM-DD')
  }

  // 表格列配置
  const columns = [
    {
      title: '品牌',
      dataIndex: '品牌',
      key: '品牌',
      width: 120,
    },
    {
      title: '品牌ID',
      dataIndex: '品牌ID',
      key: '品牌ID',
      width: 100,
    },
    {
      title: '周期类型',
      dataIndex: '周期类型',
      key: '周期类型',
      width: 100,
    },
    {
      title: '日期',
      dataIndex: '日期',
      key: '日期',
      width: 120,
    },
    {
      title: '员工姓名',
      dataIndex: '员工姓名',
      key: '员工姓名',
      width: 100,
    },
    {
      title: '店铺编号',
      dataIndex: '店铺编号',
      key: '店铺编号',
      width: 120,
    },
    {
      title: '小红书成单',
      dataIndex: '小红书成单',
      key: '小红书成单',
      width: 120,
      render: (value) => value || 0,
    },
    {
      title: '本期累计成单',
      dataIndex: '本期累计成单',
      key: '本期累计成单',
      width: 120,
      render: (value) => value || 0,
    },
    {
      title: '企微留资数',
      dataIndex: '企微留资数',
      key: '企微留资数',
      width: 100,
      render: (value) => value || 0,
    },
    {
      title: '操作',
      key: 'action',
      width: 150,
      render: (_, record) => (
        <Space size="small">
          <Button
            type="link"
            icon={<EditOutlined />}
            onClick={() => handleEdit(record)}
          >
            编辑
          </Button>
          <Popconfirm
            title="确定要删除这条销售数据吗？"
            onConfirm={() => handleDelete(record)}
            okText="确定"
            cancelText="取消"
          >
            <Button type="link" danger icon={<DeleteOutlined />}>
              删除
            </Button>
          </Popconfirm>
        </Space>
      ),
    },
  ]

  // 处理新增
  const handleAdd = () => {
    setIsEdit(false)
    form.resetFields()
    form.setFieldsValue({
      周期类型: 'BY_WEEK',
      日期: calculateDateByCycleType(new Date(), 'BY_WEEK')
    })
    setIsModalVisible(true)
  }

  // 处理编辑
  const handleEdit = (record) => {
    setIsEdit(true)
    form.setFieldsValue(record)
    setIsModalVisible(true)
  }

  // 处理删除
  const handleDelete = async (record) => {
    try {
      await deleteSalesData(
        record.品牌ID,
        record.周期类型,
        record.日期,
        record.员工姓名,
        record.店铺编号
      )
      message.success('删除成功')
    } catch (error) {
      message.error('删除失败: ' + error.message)
    }
  }

  // 处理表单提交
  const handleSubmit = async () => {
    try {
      const values = await form.validateFields()
      
      if (isEdit) {
        const originalData = form.getFieldsValue()
        await updateSalesData(
          originalData.品牌ID,
          originalData.周期类型,
          originalData.日期,
          originalData.员工姓名,
          originalData.店铺编号,
          values
        )
        message.success('更新成功')
      } else {
        await createSalesData(values)
        message.success('创建成功')
      }
      
      setIsModalVisible(false)
      form.resetFields()
    } catch (error) {
      message.error('操作失败: ' + error.message)
    }
  }

  // 处理搜索
  const handleSearch = (values) => {
    // 将周选择转换为周起始与周期类型
    let params = { ...values }
    if (values?.week) {
      const start = dayjs(values.week).startOf('isoWeek').format('YYYY-MM-DD')
      const end = dayjs(values.week).endOf('isoWeek').format('YYYY-MM-DD')
      params.startDate = start
      params.endDate = end
      params.cycleType = 'BY_WEEK'
    }
    setSearchParams(params)
    fetchSalesDataList()
    fetchStatistics()
  }

  // 处理分页
  const handleTableChange = (pagination) => {
    setPagination(pagination.current, pagination.pageSize)
    fetchSalesDataList()
  }

  // 处理批量删除
  const handleBatchDelete = async () => {
    if (selectedRowKeys.length === 0) {
      message.warning('请先选择要删除的数据')
      return
    }

    try {
      const selectedData = salesDataList.filter(item => 
        selectedRowKeys.includes(`${item.品牌ID}-${item.周期类型}-${item.日期}-${item.员工姓名}-${item.店铺编号}`)
      )
      await batchDeleteSalesData(selectedData)
      message.success('批量删除成功')
      setSelectedRowKeys([])
    } catch (error) {
      message.error('批量删除失败: ' + error.message)
    }
  }

  // 打开导入弹窗
  const openImportModal = () => {
    setImportModalVisible(true)
    importForm.resetFields()
    setImportFile(null)
    // 设置默认品牌为第一个
    const options = getBrandOptions()
    if (options && options.length > 0) {
      importForm.setFieldsValue({ brandId: options[0].value, brandName: options[0].label })
    }
    // 设置默认周期类型为按周，默认日期为“上周”的周一
    const defaultCycleType = 'BY_WEEK'
    const lastWeekMonday = dayjs().subtract(1, 'week').startOf('isoWeek')
    importForm.setFieldsValue({
      cycleType: defaultCycleType,
      date: lastWeekMonday
    })
  }

  // 选择导入文件
  const onBeforeUploadImport = (file) => {
    setImportFile(file)
    message.success(`已选择文件：${file.name}`)
    return false
  }

  // 提交导入
  const handleSubmitImport = async () => {
    try {
      setImportLoading(true)
      const values = await importForm.validateFields()
      if (!importFile) {
        message.warning('请先选择要导入的Excel文件')
        return
      }
      const excelData = await ExcelUtils.parseExcelFile(importFile)
      console.log('导入原始Excel数据:', excelData)
      const headers = ['员工姓名', '店铺编号', '小红书成单', '本期累计成单', '企微留资数']
      const { isValid, errors } = ExcelUtils.validateExcelData(excelData, headers)
      if (!isValid) {
        message.error(errors[0] || '模板校验失败')
        return
      }
      // 根据周期类型格式化日期
      let formattedDate = ''
      if (values.cycleType === 'BY_MONTH') {
        // 按月：使用该月第一天
        formattedDate = dayjs(values.date).startOf('month').format('YYYY-MM-DD')
      } else if (values.cycleType === 'BY_WEEK') {
        // 按周：使用周的起始日期（周一，isoWeek）
        formattedDate = dayjs(values.date).startOf('isoWeek').format('YYYY-MM-DD')
      } else {
        // 按日：直接使用选择的日期
        formattedDate = dayjs(values.date).format('YYYY-MM-DD')
      }
      
      const list = ExcelUtils.convertToSalesData(excelData).map(item => ({
        ...item,
        品牌: values.brandName || '',
        品牌ID: values.brandId || selectedBrandId || '',
        周期类型: values.cycleType,
        日期: formattedDate
      }))
      console.log('导入转换后的数据:', list)
      if (list.length === 0) {
        message.warning('没有可导入的数据')
        return
      }
      await batchImportSalesData(list)
      message.success(`成功导入 ${list.length} 条记录`)
      setImportModalVisible(false)
      setImportFile(null)
      fetchSalesDataList()
      fetchStatistics()
    } catch (error) {
      console.error('导入流程发生错误:', error)
      message.error('导入失败: ' + (error.message || '未知错误'))
    }
    finally {
      setImportLoading(false)
    }
  }

  // 处理Excel导出
  const handleExport = () => {
    try {
      exportToExcel(salesDataList, '销售数据')
      message.success('导出成功')
    } catch (error) {
      message.error('导出失败: ' + error.message)
    }
  }

  // 刷新数据
  const handleRefresh = () => {
    fetchSalesDataList()
    fetchStatistics()
  }

  const rowSelection = {
    selectedRowKeys,
    onChange: setSelectedRowKeys,
    getCheckboxProps: (record) => ({
      name: `${record.品牌ID}-${record.周期类型}-${record.日期}-${record.员工姓名}-${record.店铺编号}`,
    }),
  }

  return (
    <div style={{ padding: '24px' }}>
      <Card>
        {/* 搜索区域 */}
        <Form
          form={searchForm}
          layout="inline"
          onFinish={handleSearch}
          style={{ marginBottom: 16 }}
        >
          <Form.Item name="search">
            <Input
              placeholder="搜索品牌、员工或店铺"
              prefix={<SearchOutlined />}
              style={{ width: 200 }}
            />
          </Form.Item>
          <Form.Item name="brandId" initialValue={selectedBrandId}>
            <Select 
              placeholder="选择品牌" 
              style={{ width: 150 }} 
              allowClear
              onChange={(val) => setSelectedBrandId(val || '')}
            >
              {getBrandOptions().map(brand => (
                <Option key={brand.value} value={brand.value}>{brand.label}</Option>
              ))}
            </Select>
          </Form.Item>
          {/* 周期类型固定为周 */}
          <Form.Item label="周期类型">
            <Input value={'按周'} disabled style={{ width: 120 }} />
          </Form.Item>
          <Form.Item name="cycleType" initialValue={'BY_WEEK'} hidden>
            <Input />
          </Form.Item>
          <Form.Item name="week" label="周">
            <ConfigProvider locale={zhCN}>
              <DatePicker picker="week" format="YYYY-第WW周" />
            </ConfigProvider>
          </Form.Item>
          <Form.Item>
            <Button type="primary" htmlType="submit" icon={<SearchOutlined />}>
              搜索
            </Button>
          </Form.Item>
        </Form>

        {/* 操作区域 */}
        <Space style={{ marginBottom: 16 }}>
          <Button type="primary" icon={<PlusOutlined />} onClick={handleAdd}>
            新增销售数据
          </Button>
          <Button 
            icon={<DownloadOutlined />} 
            onClick={handleExport}
          >
            导出Excel
          </Button>
          <Button icon={<UploadOutlined />} onClick={openImportModal}>
              导入Excel
            </Button>
          <Button icon={<ReloadOutlined />} onClick={handleRefresh}>
            刷新
          </Button>
          {selectedRowKeys.length > 0 && (
            <Popconfirm
              title="确定要删除选中的数据吗？"
              onConfirm={handleBatchDelete}
              okText="确定"
              cancelText="取消"
            >
              <Button danger>批量删除</Button>
            </Popconfirm>
          )}
        </Space>

        {/* 统计信息 */}
        <Row gutter={16} style={{ marginBottom: 16 }}>
          <Col span={6}>
            <Card>
              <Statistic title="总成单金额" value={statistics.totalOrderAmount} />
            </Card>
          </Col>
          <Col span={6}>
            <Card>
              <Statistic title="总留资数" value={statistics.totalLeads} />
            </Card>
          </Col>
          <Col span={6}>
            <Card>
              <Statistic title="总成单数" value={statistics.totalOrders} />
            </Card>
          </Col>
          <Col span={6}>
            <Card>
              <Statistic title="平均成单金额" value={statistics.averageOrderAmount} precision={2} />
            </Card>
          </Col>
        </Row>

        {/* 表格 */}
        <Table
          columns={columns}
          dataSource={salesDataList}
          loading={loading}
          rowKey={(record) => `${record.品牌ID}-${record.周期类型}-${record.日期}-${record.员工姓名}-${record.店铺编号}`}
          rowSelection={rowSelection}
          pagination={{
            current: currentPage,
            pageSize: pageSize,
            total: total,
            showSizeChanger: true,
            showQuickJumper: true,
            showTotal: (total, range) => 
              `第 ${range[0]}-${range[1]} 条/共 ${total} 条`,
          }}
          onChange={handleTableChange}
          scroll={{ x: 1400 }}
        />
      </Card>

      {/* 新增/编辑对话框 */}
      <Modal
        title={isEdit ? '编辑销售数据' : '新增销售数据'}
        open={isModalVisible}
        onOk={handleSubmit}
        onCancel={() => {
          setIsModalVisible(false)
          form.resetFields()
        }}
        width={600}
      >
        <Form
          form={form}
          layout="vertical"
          initialValues={{
            周期类型: 'BY_WEEK',
            小红书成单: 0,
            本期累计成单: 0,
            企微留资数: 0
          }}
        >
          <Form.Item
            name="品牌"
            label="品牌"
            rules={[{ required: true, message: '请输入品牌名称' }]}
          >
            <Input placeholder="请输入品牌名称" />
          </Form.Item>
          <Form.Item
            name="品牌ID"
            label="品牌ID"
            rules={[{ required: true, message: '请输入品牌ID' }]}
          >
            <Input placeholder="请输入品牌ID" />
          </Form.Item>
          <Form.Item
            name="周期类型"
            label="周期类型"
            rules={[{ required: true, message: '请选择周期类型' }]}
          >
            <Select>
              <Option value="BY_WEEK">按周</Option>
              <Option value="BY_MONTH">按月</Option>
              <Option value="BY_DAY">按日</Option>
            </Select>
          </Form.Item>
          <Form.Item
            name="日期"
            label="日期"
            rules={[{ required: true, message: '请选择日期' }]}
          >
            <DatePicker style={{ width: '100%' }} />
          </Form.Item>
          <Form.Item
            name="员工姓名"
            label="员工姓名"
            rules={[{ required: true, message: '请输入员工姓名' }]}
          >
            <Input placeholder="请输入员工姓名" />
          </Form.Item>
          <Form.Item
            name="店铺编号"
            label="店铺编号"
            rules={[{ required: true, message: '请输入店铺编号' }]}
          >
            <Input placeholder="请输入店铺编号" />
          </Form.Item>
          <Form.Item
            name="小红书成单"
            label="小红书成单"
          >
            <InputNumber placeholder="请输入小红书成单数" style={{ width: '100%' }} min={0} />
          </Form.Item>
          <Form.Item
            name="本期累计成单"
            label="本期累计成单"
          >
            <InputNumber placeholder="请输入本期累计成单数" style={{ width: '100%' }} min={0} />
          </Form.Item>
          <Form.Item
            name="企微留资数"
            label="企微留资数"
          >
            <InputNumber placeholder="请输入企微留资数" style={{ width: '100%' }} min={0} />
          </Form.Item>
        </Form>
      </Modal>
      {/* 导入对话框 */}
      <Modal
        title="导入销售数据"
        open={importModalVisible}
        onOk={handleSubmitImport}
        onCancel={() => { setImportModalVisible(false); setImportFile(null) }}
        width={520}
        confirmLoading={importLoading}
      >
        <Form form={importForm} layout="vertical" initialValues={{ cycleType: 'BY_WEEK' }}>
          <Form.Item name="brandId" label="品牌" rules={[{ required: true, message: '请选择品牌' }]}> 
            <Select 
              placeholder="选择品牌" 
              options={getBrandOptions()}
              onChange={(val, option) => importForm.setFieldsValue({ brandName: option?.label })}
            />
          </Form.Item>
          <Form.Item name="brandName" hidden>
            <Input />
          </Form.Item>
          {/* 周期类型固定为按周 */}
          <Form.Item name="cycleType" label="周期类型">
            <Input value={'按周'} disabled />
          </Form.Item>
          <Form.Item name="cycleType" hidden>
            <Input value="BY_WEEK" />
          </Form.Item>
          <Form.Item 
            name="date" 
            label="日期（按周）" 
            rules={[{ required: true, message: '请选择周' }]}
          > 
            <ConfigProvider locale={zhCN}>
              <DatePicker 
                picker="week"
                style={{ width: '100%' }}
                format={(value) => {
                  if (!value) return ''
                  const start = dayjs(value).startOf('isoWeek')
                  const end = dayjs(value).endOf('isoWeek')
                  return `${start.format('YYYY-MM-DD')} ~ ${end.format('YYYY-MM-DD')}`
                }}
                onChange={(date) => {
                  if (date) {
                    const weekStart = dayjs(date).startOf('isoWeek') // 周一（北京时间）
                    importForm.setFieldsValue({ date: weekStart })
                  }
                }}
              />
            </ConfigProvider>
          </Form.Item>
          <Form.Item label="Excel 文件" required>
            <Upload accept=".xlsx,.xls" beforeUpload={onBeforeUploadImport} showUploadList={false}>
              <Button icon={<UploadOutlined />}>选择文件</Button>
            </Upload>
            <div style={{ marginTop: 8, color: '#666' }}>
              {importFile ? `已选择：${importFile.name}` : '未选择文件'}
            </div>
          </Form.Item>
          <div style={{ color: '#999' }}>
            模板字段：员工姓名、店铺编号、小红书成单、本期累计成单、企微留资数。品牌/周期/日期在此弹窗选择。
          </div>
        </Form>
      </Modal>
    </div>
  )
}

// src/views/SalesData.vue
<template>
  <div class="sales-data-container">
    <!-- 页面头部 -->
    <div class="page-header">
      <div class="header-left">
        <h1>KOS销售数据管理</h1>
        <p>管理品牌离线导入的KOS销售数据</p>
      </div>
      <div class="header-right">
        <el-button type="success" @click="showImportDialog = true">
          <el-icon><Upload /></el-icon>
          Excel导入
        </el-button>
        <el-button type="primary" @click="handleExport">
          <el-icon><Download /></el-icon>
          导出数据
        </el-button>
      </div>
    </div>

    <!-- 搜索和筛选 -->
    <div class="search-section">
      <el-card>
        <el-form :model="searchForm" class="search-form">
          <el-row :gutter="16">
            <el-col :xs="24" :sm="12" :md="8" :lg="6" :xl="5">
              <el-form-item label="搜索">
                <el-input
                  v-model="searchForm.search"
                  placeholder="品牌、员工姓名或店铺编号"
                  clearable
                  class="search-input"
                  @keyup.enter="handleSearch"
                >
                  <template #prefix>
                    <el-icon><Search /></el-icon>
                  </template>
                </el-input>
              </el-form-item>
            </el-col>
            
            <el-col :xs="24" :sm="12" :md="8" :lg="6" :xl="5">
              <el-form-item label="品牌">
                <el-select 
                  v-model="searchForm.brandId" 
                  placeholder="选择品牌" 
                  clearable
                  class="filter-select"
                >
                  <el-option
                    v-for="brand in brandList"
                    :key="brand"
                    :label="brand"
                    :value="brand"
                  />
                </el-select>
              </el-form-item>
            </el-col>
            
            <el-col :xs="24" :sm="12" :md="8" :lg="6" :xl="5">
              <el-form-item label="周期类型">
                <el-input 
                  v-model="searchForm.cycleType" 
                  placeholder="输入周期类型" 
                  clearable
                  class="filter-select"
                />
              </el-form-item>
            </el-col>
            
            <el-col :xs="24" :sm="12" :md="8" :lg="6" :xl="5">
              <el-form-item label="日期范围">
                <el-date-picker
                  v-model="dateRange"
                  type="daterange"
                  range-separator="至"
                  start-placeholder="开始日期"
                  end-placeholder="结束日期"
                  format="YYYY-MM-DD"
                  value-format="YYYY-MM-DD"
                  class="date-picker"
                  @change="handleDateRangeChange"
                />
              </el-form-item>
            </el-col>
            
            <el-col :xs="24" :sm="24" :md="24" :lg="24" :xl="4">
              <el-form-item class="search-buttons">
                <el-button type="primary" @click="handleSearch" class="search-btn">
                  <el-icon><Search /></el-icon>
                  搜索
                </el-button>
                <el-button @click="handleReset" class="reset-btn">
                  <el-icon><Refresh /></el-icon>
                  重置
                </el-button>
              </el-form-item>
            </el-col>
          </el-row>
        </el-form>
      </el-card>
    </div>

    <!-- 统计信息 -->
    <div class="stats-section">
      <el-row :gutter="20">
        <el-col :span="6">
          <el-card class="stats-card">
            <div class="stats-content">
              <div class="stats-icon amount">
                <el-icon><Money /></el-icon>
              </div>
              <div class="stats-info">
                <div class="stats-number">{{ formatMoney(statistics.totalOrderAmount) }}</div>
                <div class="stats-label">总成单金额</div>
              </div>
            </div>
          </el-card>
        </el-col>
        <el-col :span="6">
          <el-card class="stats-card">
            <div class="stats-content">
              <div class="stats-icon leads">
                <el-icon><UserFilled /></el-icon>
              </div>
              <div class="stats-info">
                <div class="stats-number">{{ statistics.totalLeads }}</div>
                <div class="stats-label">总留资数</div>
              </div>
            </div>
          </el-card>
        </el-col>
        <el-col :span="6">
          <el-card class="stats-card">
            <div class="stats-content">
              <div class="stats-icon orders">
                <el-icon><ShoppingCart /></el-icon>
              </div>
              <div class="stats-info">
                <div class="stats-number">{{ statistics.totalOrders }}</div>
                <div class="stats-label">总成单数</div>
              </div>
            </div>
          </el-card>
        </el-col>
        <el-col :span="6">
          <el-card class="stats-card">
            <div class="stats-content">
              <div class="stats-icon average">
                <el-icon><TrendCharts /></el-icon>
              </div>
              <div class="stats-info">
                <div class="stats-number">{{ formatMoney(statistics.averageOrderAmount) }}</div>
                <div class="stats-label">平均成单金额</div>
              </div>
            </div>
          </el-card>
        </el-col>
      </el-row>
    </div>

    <!-- 数据表格 -->
    <div class="table-section">
      <el-card>
        <div class="table-header">
          <div class="table-title">销售数据列表</div>
          <div class="table-actions">
            <el-button 
              type="danger" 
              :disabled="selectedRows.length === 0"
              @click="handleBatchDelete"
            >
              <el-icon><Delete /></el-icon>
              批量删除
            </el-button>
          </div>
        </div>
        
        <div class="table-wrapper">
        <el-table
          v-loading="loading"
          :data="salesDataList"
          @selection-change="handleSelectionChange"
          stripe
          border
        >
          <el-table-column type="selection" min-width="55" />
          
          <el-table-column prop="品牌" label="品牌" min-width="120" />
          <el-table-column prop="品牌ID" label="品牌ID" min-width="100" />
          <el-table-column prop="周期类型" label="周期类型" min-width="100" />
          
          <el-table-column prop="日期" label="日期" min-width="120" />
          <el-table-column prop="短日期" label="短日期" min-width="120" />
          <el-table-column prop="员工姓名" label="员工姓名" min-width="120" />
          <el-table-column prop="店铺编号" label="店铺编号" min-width="120" />
          
          <el-table-column prop="小红书成单" label="小红书成单" min-width="140">
            <template #default="{ row }">
              <span class="money-text">¥{{ formatMoney(row.小红书成单) }}</span>
            </template>
          </el-table-column>
          
          <el-table-column prop="本期累计成单" label="本期累计成单" min-width="140" />
          <el-table-column prop="企微留资数" label="企微留资数" min-width="120" />
          
          
          <el-table-column label="操作" min-width="120" fixed="right">
            <template #default="{ row }">
              <div class="action-buttons">
                <el-tooltip content="编辑" placement="top">
                  <el-button 
                    type="primary" 
                    size="small" 
                    circle
                    @click="handleEdit(row)"
                  >
                    <el-icon><Edit /></el-icon>
                  </el-button>
                </el-tooltip>
                
                <el-tooltip content="删除" placement="top">
                  <el-button 
                    type="danger" 
                    size="small" 
                    circle
                    @click="handleDelete(row)"
                  >
                    <el-icon><Delete /></el-icon>
                  </el-button>
                </el-tooltip>
              </div>
            </template>
          </el-table-column>
        </el-table>
        </div>
        
        <!-- 分页 -->
        <div class="pagination-section">
          <el-pagination
            v-model:current-page="currentPage"
            v-model:page-size="pageSize"
            :page-sizes="[20, 50, 100, 200]"
            :total="total"
            layout="total, sizes, prev, pager, next, jumper"
            @size-change="handleSizeChange"
            @current-change="handleCurrentChange"
          />
        </div>
      </el-card>
    </div>

    <!-- Excel导入对话框 -->
    <el-dialog
      v-model="showImportDialog"
      title="Excel导入"
      width="800px"
      @close="handleImportDialogClose"
    >
      <div class="import-content">
        <el-steps :active="importStep" finish-status="success">
          <el-step title="选择文件" />
          <el-step title="数据预览" />
          <el-step title="导入完成" />
        </el-steps>
        
        <div class="step-content">
          <!-- 步骤1: 选择文件 -->
          <div v-if="importStep === 0" class="step-1">
            <el-upload
              ref="uploadRef"
              :auto-upload="false"
              :on-change="handleFileChange"
              :before-upload="beforeUpload"
              accept=".xlsx,.xls"
              drag
            >
              <el-icon class="el-icon--upload"><upload-filled /></el-icon>
              <div class="el-upload__text">
                将文件拖到此处，或<em>点击上传</em>
              </div>
              <template #tip>
                <div class="el-upload__tip">
                  只能上传xlsx/xls文件，且不超过10MB
                </div>
              </template>
            </el-upload>
            
            <div class="template-download">
              <el-button type="text" @click="downloadTemplate">
                <el-icon><Download /></el-icon>
                下载导入模板
              </el-button>
            </div>
          </div>
          
          <!-- 步骤2: 数据预览 -->
          <div v-if="importStep === 1" class="step-2">
            <div class="preview-header">
              <h4>数据预览 (共{{ previewData.length }}条记录)</h4>
              <el-button type="primary" @click="handleImport" :loading="importing">
                <el-icon><Upload /></el-icon>
                确认导入
              </el-button>
            </div>
            
            <el-table :data="previewData.slice(0, 10)" border max-height="400">
              <el-table-column prop="品牌" label="品牌" width="100" />
              <el-table-column prop="品牌ID" label="品牌ID" width="100" />
              <el-table-column prop="周期类型" label="周期类型" width="100" />
              <el-table-column prop="日期" label="日期" width="120" />
              <el-table-column prop="短日期" label="短日期" width="120" />
              <el-table-column prop="员工姓名" label="员工姓名" width="120" />
              <el-table-column prop="店铺编号" label="店铺编号" width="120" />
              <el-table-column prop="小红书成单" label="小红书成单" width="120" />
              <el-table-column prop="本期累计成单" label="本期累计成单" width="120" />
              <el-table-column prop="企微留资数" label="企微留资数" width="120" />
            </el-table>
            
            <div v-if="previewData.length > 10" class="preview-tip">
              仅显示前10条记录，实际将导入{{ previewData.length }}条记录
            </div>
          </div>
          
          <!-- 步骤3: 导入完成 -->
          <div v-if="importStep === 2" class="step-3">
            <el-result
              :icon="importResult.success ? 'success' : 'error'"
              :title="importResult.success ? '导入成功' : '导入失败'"
              :sub-title="importResult.message"
            >
              <template #extra>
                <el-button type="primary" @click="showImportDialog = false">
                  完成
                </el-button>
                <el-button @click="resetImport">
                  重新导入
                </el-button>
              </template>
            </el-result>
          </div>
        </div>
      </div>
    </el-dialog>

    <!-- 编辑对话框 -->
    <el-dialog
      v-model="showEditDialog"
      title="编辑销售数据"
      width="600px"
      @close="handleEditDialogClose"
    >
      <el-form
        ref="editFormRef"
        :model="editFormData"
        :rules="editFormRules"
        label-width="120px"
      >
        <el-row :gutter="20">
          <el-col :span="12">
            <el-form-item label="品牌" prop="品牌">
              <el-input v-model="editFormData.品牌" placeholder="请输入品牌名称" />
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="品牌ID" prop="品牌ID">
              <el-input v-model="editFormData.品牌ID" placeholder="请输入品牌ID" />
            </el-form-item>
          </el-col>
        </el-row>
        
        <el-row :gutter="20">
          <el-col :span="12">
            <el-form-item label="周期类型" prop="周期类型">
              <el-input v-model="editFormData.周期类型" placeholder="请输入周期类型" />
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="员工姓名" prop="员工姓名">
              <el-input v-model="editFormData.员工姓名" placeholder="请输入员工姓名" />
            </el-form-item>
          </el-col>
        </el-row>
        
        <el-row :gutter="20">
          <el-col :span="12">
            <el-form-item label="日期" prop="日期">
              <el-input v-model="editFormData.日期" placeholder="请输入日期" />
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="短日期" prop="短日期">
              <el-input v-model="editFormData.短日期" placeholder="请输入短日期" />
            </el-form-item>
          </el-col>
        </el-row>
        
        <el-form-item label="店铺编号" prop="店铺编号">
          <el-input v-model="editFormData.店铺编号" placeholder="请输入店铺编号" />
        </el-form-item>
        
        <el-row :gutter="20">
          <el-col :span="12">
            <el-form-item label="小红书成单" prop="小红书成单">
              <el-input-number 
                v-model="editFormData.小红书成单" 
                :precision="2" 
                :min="0" 
                :max="999999999.99"
                style="width: 100%"
              />
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="本期累计成单" prop="本期累计成单">
              <el-input-number 
                v-model="editFormData.本期累计成单" 
                :min="0" 
                :max="999999"
                style="width: 100%"
              />
            </el-form-item>
          </el-col>
        </el-row>
        
        <el-form-item label="企微留资数" prop="企微留资数">
          <el-input-number 
            v-model="editFormData.企微留资数" 
            :min="0" 
            :max="999999"
            style="width: 100%"
          />
        </el-form-item>
      </el-form>
      
      <template #footer>
        <el-button @click="showEditDialog = false">取消</el-button>
        <el-button type="primary" @click="handleEditSubmit" :loading="editSubmitting">
          更新
        </el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup>
import { ref, reactive, onMounted, computed } from 'vue'
import { useSalesDataStore } from '@/stores/salesData'
import { MessageUtils, FormUtils, DataUtils } from '@/utils/common'
import { ExcelUtils } from '@/utils/excel'

const salesDataStore = useSalesDataStore()

// 响应式数据
const loading = computed(() => salesDataStore.loading)
const salesDataList = computed(() => salesDataStore.salesDataList)
const total = computed(() => salesDataStore.total)
const currentPage = computed({
  get: () => salesDataStore.currentPage,
  set: (value) => salesDataStore.setPagination(value, pageSize.value)
})
const pageSize = computed({
  get: () => salesDataStore.pageSize,
  set: (value) => salesDataStore.setPagination(currentPage.value, value)
})
const brandList = computed(() => salesDataStore.brandList)
const statistics = computed(() => salesDataStore.statistics)

// 搜索表单
const searchForm = reactive({
  search: '',
  brandId: '',
  cycleType: '',
  startDate: '',
  endDate: ''
})

const dateRange = ref([])

// 表格选择
const selectedRows = ref([])

// 导入相关
const showImportDialog = ref(false)
const importStep = ref(0)
const previewData = ref([])
const importing = ref(false)
const importResult = ref({ success: false, message: '' })

// 编辑相关
const showEditDialog = ref(false)
const editSubmitting = ref(false)
// 保存原始复合主键信息，用于更新匹配
const originalKeys = ref({ 品牌ID: '', 周期类型: '', 短日期: '', 员工姓名: '', 店铺编号: '' })
const editFormData = reactive({
  品牌: '',
  品牌ID: '',
  周期类型: '',
  日期: '',
  短日期: '',
  员工姓名: '',
  店铺编号: '',
  小红书成单: 0,
  本期累计成单: 0,
  企微留资数: 0
})

const editFormRules = {
  品牌: [
    { required: true, message: '请输入品牌名称', trigger: 'blur' }
  ],
  品牌ID: [
    { required: true, message: '请输入品牌ID', trigger: 'blur' }
  ],
  员工姓名: [
    { required: true, message: '请输入员工姓名', trigger: 'blur' }
  ]
}

const editFormRef = ref()
const uploadRef = ref()

// 方法
const fetchData = async () => {
  try {
    await salesDataStore.fetchSalesDataList()
    await salesDataStore.fetchStatistics()
  } catch (error) {
    MessageUtils.error(error.message)
  }
}

const handleSearch = () => {
  salesDataStore.setSearchParams(searchForm)
  fetchData()
}

const handleReset = () => {
  Object.assign(searchForm, {
    search: '',
    brandId: '',
    cycleType: '',
    startDate: '',
    endDate: ''
  })
  dateRange.value = []
  salesDataStore.setSearchParams(searchForm)
  fetchData()
}

const handleDateRangeChange = (dates) => {
  if (dates && dates.length === 2) {
    searchForm.startDate = dates[0]
    searchForm.endDate = dates[1]
  } else {
    searchForm.startDate = ''
    searchForm.endDate = ''
  }
}

const handleSizeChange = (size) => {
  pageSize.value = size
  fetchData()
}

const handleCurrentChange = (page) => {
  currentPage.value = page
  fetchData()
}

const handleSelectionChange = (selection) => {
  selectedRows.value = selection
}

const handleEdit = (row) => {
  Object.assign(editFormData, row)
  originalKeys.value = {
    品牌ID: row.品牌ID,
    周期类型: row.周期类型,
    短日期: row.短日期,
    员工姓名: row.员工姓名,
    店铺编号: row.店铺编号
  }
  showEditDialog.value = true
}

const handleDelete = async (row) => {
  try {
    await MessageUtils.confirmDelete(`销售数据记录`)
    await salesDataStore.deleteSalesData(
      row.品牌ID,
      row.周期类型,
      row.短日期,
      row.员工姓名,
      row.店铺编号
    )
    MessageUtils.success('删除成功')
    fetchData()
  } catch (error) {
    if (error !== 'cancel') {
      MessageUtils.error(error.message)
    }
  }
}

const handleBatchDelete = async () => {
  try {
    await MessageUtils.confirmBatchOperation('删除', selectedRows.value.length)
    await salesDataStore.batchDeleteSalesData(selectedRows.value)
    MessageUtils.success('批量删除成功')
    fetchData()
  } catch (error) {
    if (error !== 'cancel') {
      MessageUtils.error(error.message)
    }
  }
}

const handleExport = () => {
  ExcelUtils.exportToExcel(salesDataList.value, '销售数据')
  MessageUtils.success('导出成功')
}

const handleFileChange = async (file) => {
  try {
    const excelData = await ExcelUtils.parseExcelFile(file.raw)
    const headers = ['品牌', '品牌ID', '周期类型', '日期', '短日期', '员工姓名', '店铺编号', '小红书成单', '本期累计成单', '企微留资数']
    
    const validation = ExcelUtils.validateExcelData(excelData, headers)
    if (!validation.isValid) {
      MessageUtils.error(`数据验证失败:\n${validation.errors.join('\n')}`)
      return
    }
    
    previewData.value = ExcelUtils.convertToSalesData(excelData)
    importStep.value = 1
  } catch (error) {
    MessageUtils.error(error.message)
  }
}

const beforeUpload = (file) => {
  const isExcel = file.type === 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' || 
                  file.type === 'application/vnd.ms-excel'
  if (!isExcel) {
    MessageUtils.error('只能上传Excel文件!')
    return false
  }
  
  const isLt10M = file.size / 1024 / 1024 < 10
  if (!isLt10M) {
    MessageUtils.error('文件大小不能超过10MB!')
    return false
  }
  
  return false // 阻止自动上传
}

const handleImport = async () => {
  try {
    importing.value = true
    await salesDataStore.batchImportSalesData(previewData.value)
    
    importResult.value = {
      success: true,
      message: `成功导入${previewData.value.length}条记录`
    }
    importStep.value = 2
    
    MessageUtils.success('导入成功')
    fetchData()
  } catch (error) {
    importResult.value = {
      success: false,
      message: error.message
    }
    importStep.value = 2
    MessageUtils.error(error.message)
  } finally {
    importing.value = false
  }
}

const handleEditSubmit = async () => {
  console.log('=== 开始提交销售数据编辑 ===')
  console.log('编辑数据:', editFormData)
  
  try {
    console.log('开始表单验证...')
    await editFormRef.value.validate()
    console.log('✓ 表单验证通过')
    
    editSubmitting.value = true
    console.log('开始更新数据...')
    
    await salesDataStore.updateSalesData(
      originalKeys.value.品牌ID,
      originalKeys.value.周期类型,
      originalKeys.value.短日期,
      originalKeys.value.员工姓名,
      originalKeys.value.店铺编号,
      editFormData
    )
    MessageUtils.success('更新成功')
    console.log('✓ 更新成功')
    
    console.log('关闭对话框...')
    showEditDialog.value = false
    console.log('刷新数据...')
    fetchData()
    console.log('=== 编辑完成 ===')
  } catch (error) {
    console.error('编辑失败:', error)
    if (error && error.message) {
      MessageUtils.error(error.message)
    } else {
      MessageUtils.error('操作失败，请检查表单数据')
    }
  } finally {
    editSubmitting.value = false
  }
}

const handleImportDialogClose = () => {
  resetImport()
}

const handleEditDialogClose = () => {
  Object.assign(editFormData, {
    品牌: '',
    品牌ID: '',
    周期类型: '',
    日期: '',
    短日期: '',
    员工姓名: '',
    店铺编号: '',
    小红书成单: 0,
    本期累计成单: 0,
    企微留资数: 0
  })
  editFormRef.value?.resetFields()
}

const resetImport = () => {
  importStep.value = 0
  previewData.value = []
  importResult.value = { success: false, message: '' }
  uploadRef.value?.clearFiles()
}

const downloadTemplate = () => {
  const templateData = [
    ['品牌', '品牌ID', '周期类型', '日期', '短日期', '员工姓名', '店铺编号', '小红书成单', '本期累计成单', '企微留资数'],
    ['示例品牌', '001', 'day', '2024-01-01', '2024-01-01', '张三', '001', '1000.00', '100', '10']
  ]
  
  const worksheet = XLSX.utils.aoa_to_sheet(templateData)
  const workbook = XLSX.utils.book_new()
  XLSX.utils.book_append_sheet(workbook, worksheet, '销售数据模板')
  
  XLSX.writeFile(workbook, '销售数据导入模板.xlsx')
  MessageUtils.success('模板下载成功')
}

// 移除周期类型枚举逻辑，允许自由输入

const formatMoney = DataUtils.formatMoney
const formatDateTime = DataUtils.formatDateTime

// 生命周期
onMounted(() => {
  fetchData()
})
</script>

<style scoped>
.sales-data-container {
  padding: 20px;
  background-color: #f5f7fa;
  min-height: 100vh;
}

.page-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 20px;
  padding: 20px;
  background: white;
  border-radius: 8px;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
}

.header-left h1 {
  margin: 0 0 8px 0;
  color: #303133;
  font-size: 24px;
  font-weight: 600;
}

.header-left p {
  margin: 0;
  color: #909399;
  font-size: 14px;
}

.search-section {
  margin-bottom: 20px;
}

.search-form {
  padding: 8px 0;
}

.search-input {
  width: 100%;
  min-width: 200px;
}

.filter-select {
  width: 100%;
  min-width: 150px;
}

.date-picker {
  width: 100%;
  min-width: 200px;
}

.search-buttons {
  display: flex;
  gap: 8px;
  justify-content: flex-end;
  margin-bottom: 0 !important;
}

.search-btn,
.reset-btn {
  min-width: 80px;
  height: 32px;
}

/* 操作按钮样式 */
.action-buttons {
  display: flex;
  gap: 8px;
  justify-content: center;
  align-items: center;
}

.action-buttons .el-button {
  width: 32px;
  height: 32px;
  padding: 0;
  display: flex;
  align-items: center;
  justify-content: center;
}

.action-buttons .el-button .el-icon {
  font-size: 14px;
}

/* 响应式优化 */
@media (max-width: 768px) {
  .action-buttons {
    gap: 4px;
  }
  
  .action-buttons .el-button {
    width: 28px;
    height: 28px;
  }
  
  .action-buttons .el-button .el-icon {
    font-size: 12px;
  }
}

@media (max-width: 576px) {
  .search-buttons {
    flex-direction: column;
    gap: 8px;
  }
  
  .search-btn,
  .reset-btn {
    width: 100%;
  }
}

.stats-section {
  margin-bottom: 20px;
}

.stats-card {
  border: none;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
}

.stats-content {
  display: flex;
  align-items: center;
  padding: 10px 0;
}

.stats-icon {
  width: 60px;
  height: 60px;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  margin-right: 16px;
  font-size: 24px;
  color: white;
}

.stats-icon.amount {
  background: linear-gradient(135deg, #67c23a, #85ce61);
}

.stats-icon.leads {
  background: linear-gradient(135deg, #409eff, #66b1ff);
}

.stats-icon.orders {
  background: linear-gradient(135deg, #e6a23c, #ebb563);
}

.stats-icon.average {
  background: linear-gradient(135deg, #f56c6c, #f78989);
}

.stats-info {
  flex: 1;
}

.stats-number {
  font-size: 28px;
  font-weight: 600;
  color: #303133;
  line-height: 1;
  margin-bottom: 4px;
}

.stats-label {
  font-size: 14px;
  color: #909399;
}

.table-section {
  margin-bottom: 20px;
}

.table-wrapper {
  width: 100%;
  overflow-x: auto;
}

.table-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 16px;
}

.table-title {
  font-size: 16px;
  font-weight: 600;
  color: #303133;
}

.table-actions {
  display: flex;
  gap: 8px;
}

.pagination-section {
  margin-top: 20px;
  display: flex;
  justify-content: center;
}

.money-text {
  color: #67c23a;
  font-weight: 600;
}

.import-content {
  padding: 20px 0;
}

.step-content {
  margin-top: 30px;
}

.step-1 {
  text-align: center;
}

.template-download {
  margin-top: 20px;
}

.step-2 {
  margin-top: 20px;
}

.preview-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 20px;
}

.preview-header h4 {
  margin: 0;
  color: #303133;
}

.preview-tip {
  margin-top: 10px;
  text-align: center;
  color: #909399;
  font-size: 14px;
}

.step-3 {
  text-align: center;
}

:deep(.el-card__body) {
  padding: 20px;
}

:deep(.el-table) {
  border-radius: 8px;
  overflow: hidden;
}

:deep(.el-table th) {
  background-color: #f5f7fa;
  color: #303133;
  font-weight: 600;
}

:deep(.el-table td) {
  padding: 12px 0;
}

:deep(.el-pagination) {
  justify-content: center;
}

:deep(.el-upload-dragger) {
  width: 100%;
  height: 200px;
}

:deep(.el-upload__text) {
  margin-top: 20px;
}
</style>
